export const odourFaqs = [
  { q: "How does professional odour removal work?", a: "Professional odour removal starts by considering the likely source of the smell and the material affected. Treatment can then be focused on suitable areas rather than simply masking the odour with fragrance." },
  { q: "Can you remove every bad smell completely?", a: "Complete removal cannot be guaranteed in every situation. Results depend on the source, how long it has been present and whether contamination has travelled below the visible surface." },
  { q: "Do you provide carpet odour removal?", a: "Yes. Carpet odour removal can be considered for smells linked to spills, pets and other suitable sources. The carpet and affected area should be assessed before treatment." },
  { q: "Can you remove pet smells from carpets?", a: "Professional pet odour removal can help where carpets have been affected by pet accidents or repeated pet use. Results depend on how deeply contamination has travelled." },
  { q: "What if pet urine has reached the carpet underlay?", a: "If liquid has travelled through the carpet and into the underlay or subfloor, surface treatment alone may not completely resolve the smell. We prefer to explain this possibility rather than guarantee a result before assessment." },
  { q: "Can you remove smells from sofas?", a: "Suitable fabric furniture can be assessed for sofa odour removal. The cause of the smell and the upholstery material will influence the treatment approach." },
  { q: "Do you provide upholstery odour removal?", a: "Yes. Upholstery odour removal may be suitable for furniture affected by certain spills, pets and everyday build-up, depending on the fabric and source." },
  { q: "Can smoke smells be removed from soft furnishings?", a: "Professional smoke odour removal may help reduce smells held within suitable carpets, rugs and upholstery. Heavy or long-term smoke exposure can affect multiple surfaces, so the final result depends on the extent of contamination." },
  { q: "Can food smells be removed from carpets or furniture?", a: "Where food or drink residues have affected suitable materials, food odour removal treatment may help. The source should ideally be identified so the affected area can be treated properly." },
  { q: "Can you remove musty smells?", a: "A musty smell can have different causes. Musty smell removal should only be considered after thinking about why the smell is present. If there is an ongoing damp or moisture issue, that underlying problem needs to be addressed rather than simply treating the smell." },
  { q: "Why does an odour return after cleaning?", a: "The source may sit deeper than the surface that was cleaned. Liquids can reach carpet backing, underlay, cushions or other materials, allowing the smell to return." },
  { q: "What information should I provide when asking for odour treatment?", a: "Tell us what you think caused the smell, which item or area is affected, how long it has been present, whether pets are involved and what cleaning products have been used. Photos can also help us understand the situation." },
];
